name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main # Change this to your deployment branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Change to your Node.js version if required

    # Install dependencies
    - name: Install dependencies
      run: npm install
      
    # Install Netlify CLI
    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    # Build the project
    - name: Build the project
      run: npm run build # Replace with your build command

    # Deploy to Netlify
    - name: Deploy to Netlify
      run: |
        npx netlify deploy --dir=dist --auth=nfp_dATR9nw3KVQe4oEfv3U6YpENVMx4cfCta6c6 --site=43e53a9b-dc8c-435e-95f9-b4312e0615bc --message "GitHub Actions Deployment"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
