name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main # Change this to your deployment branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Change to your Node.js version if required

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the project
    - name: Build the project
      run: npm run build # Replace with your build command

    # Deploy to Netlify
    - name: Deploy to Netlify
      run: |
        npx netlify deploy --dir=dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID --message "GitHub Actions Deployment"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
